server:
  port: 8081

gg:
  jte:
    templateLocation: src/main/resources/jte
    developmentMode: true
    use-compiled-classes: false

spring:
  application:
    name: mentee-power-crm
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.springframework.web: DEBUG
    gg.jte: DEBUG